[build-system]
requires = ["setuptools>=77", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "podbench"
description = "Rapid Kubernetes attach and hotfix prototype"
dependencies = ["typer>=0.12"]
dynamic = ["version"]
license = "Apache-2.0"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
podbench = "podbench.__main__:main"

[project.urls]
GitHub = "https://github.com/gilesknap/podbench"

[[project.authors]]
name = "Giles Knap"
email = "gilesknap@gmail.com"

[tool.setuptools_scm]
version_file = "src/podbench/_version.py"
