"""Tests for the generated ssh configuration.

These are mostly exact-string tests on purpose. Every flag asserted here has a
silent failure mode measured in ``docs/explanations/spikes/s1.md``, so the
regression that matters is a well-meaning tidy-up, not a crash.
"""

from __future__ import annotations

import stat
from pathlib import Path

import pytest

from podbench.agent import passwd_line
from podbench.launcher import DEFAULT_SEAT_USER
from podbench.model import ContainerRef, PodRef
from podbench.sshcfg import (
    CONTROL_PATH,
    FALLBACK_HOME_PREFIX,
    SEAT_USER,
    SUN_PATH_MAX,
    HostKeyBinding,
    HostKeyPolicy,
    KubectlInvocation,
    SshdLayout,
    client_config,
    control_path_ok,
    default_home,
    ensure_control_dir,
    expanded_control_path_length,
    forge_known_hosts,
    git_remote_hosts,
    host_key_alias,
    known_hosts_entry,
    proxy_command,
    proxy_command_string,
    remote_host,
    seat_control_path,
    sshd_config,
    unsafe_set_env,
)


def _no_home() -> Path:
    """What ``Path.home()`` does when $HOME is unset and the uid is not in
    /etc/passwd — the normal state of a ``runAsUser: <target uid>`` container."""
    raise RuntimeError("Could not determine home directory.")


TARGET = ContainerRef(PodRef("prod", "api-7f9c"), "podbench")
ROOT = SshdLayout.for_uid(0)
NON_ROOT = SshdLayout.for_uid(1000, home="/home/dev")


def test_root_layout_needs_privsep_dir() -> None:
    assert ROOT.privsep_dir == "/run/sshd"
    assert ROOT.host_key_path == "/etc/ssh/ssh_host_ed25519_key"


def test_non_root_layout_is_user_relative_and_needs_no_privsep_dir() -> None:
    # sshd skips privilege separation when it is not uid 0, which is what keeps
    # a PSA-restricted debug container viable.
    assert NON_ROOT.privsep_dir is None
    assert NON_ROOT.host_key_path.startswith("/home/dev/")
    assert NON_ROOT.config_path.startswith("/home/dev/")
    assert NON_ROOT.authorized_keys_path.startswith("/home/dev/")


def test_non_root_layout_survives_a_container_with_no_home(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The shape of the degraded rung: a uid with no passwd entry and no $HOME.

    ``Path.home()`` raises there, and the agent used to die on the layout call
    before it could run a single check.
    """
    monkeypatch.delenv("HOME", raising=False)
    monkeypatch.setattr(Path, "home", _no_home)

    layout = SshdLayout.for_uid(65532)
    assert layout.home == f"{FALLBACK_HOME_PREFIX}65532"
    assert layout.config_path == "/tmp/podbench-65532/.podbench/sshd_config"
    assert layout.authorized_keys_path.startswith("/tmp/podbench-65532/")
    # A home under /tmp is only usable because sshd's ownership audit is off.
    assert "StrictModes no\n" in sshd_config(layout)


def test_home_is_taken_from_the_environment_before_the_fallback(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("HOME", "/workspace")
    monkeypatch.setattr(Path, "home", _no_home)
    assert default_home(65532) == "/workspace"
    assert SshdLayout.for_uid(65532).home == "/workspace"


def test_an_explicit_home_still_wins(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("HOME", raising=False)
    monkeypatch.setattr(Path, "home", _no_home)
    assert SshdLayout.for_uid(1000, home="/home/dev").home == "/home/dev"
    # The root layout never consults a home directory it was not given.
    assert SshdLayout.for_uid(0).home == "/root"


def test_both_halves_agree_on_the_seat_login_name() -> None:
    """The one string the agent and the launcher must spell identically.

    The agent writes a passwd record under this name for whatever uid and gid
    the seat turned out to run as; the client stanza puts the same name in
    ``User``. sshd resolves what the client offered through NSS *before* it
    looks at a key, so a disagreement is not a wrong username in a prompt — it
    is ``Permission denied (publickey)``, pointing at the key.
    """
    entry = passwd_line(uid=1000, gid=0, home="/tmp/podbench-home")
    assert entry.split(":")[0] == SEAT_USER
    assert DEFAULT_SEAT_USER == SEAT_USER

    stanza = client_config(
        TARGET,
        host_alias="podbench-demo-target",
        identity_file="~/.ssh/id_ed25519",
        host_key=HostKeyBinding.per_attach(
            "pod-uid", "/tmp/known_hosts", "ssh-ed25519 AAAA"
        ),
        layout=NON_ROOT,
        user=DEFAULT_SEAT_USER,
    )
    assert f"    User {SEAT_USER}\n" in stanza


def test_sshd_config_root_variant() -> None:
    assert sshd_config(ROOT) == (
        "# Generated by podbench. Regenerated at container start; do not edit.\n"
        "HostKey /etc/ssh/ssh_host_ed25519_key\n"
        "PermitRootLogin prohibit-password\n"
        "AuthorizedKeysFile /root/.ssh/authorized_keys\n"
        "UsePAM no\n"
        "PasswordAuthentication no\n"
        "Subsystem sftp /usr/lib/openssh/sftp-server\n"
    )


def test_sshd_config_non_root_variant() -> None:
    text = sshd_config(NON_ROOT)
    assert "StrictModes no\n" in text
    assert "PermitRootLogin" not in text
    assert "HostKey /home/dev/.podbench/ssh_host_ed25519_key\n" in text


def test_sshd_config_never_sets_a_pidfile() -> None:
    # sshd -i never writes one, so a PidFile directive is noise that invites
    # somebody to build a liveness check on a file that does not exist.
    assert "PidFile" not in sshd_config(ROOT)
    assert "PidFile" not in sshd_config(NON_ROOT)


def test_proxy_command_is_the_exact_measured_shape() -> None:
    assert proxy_command(TARGET, layout=ROOT) == [
        "kubectl",
        "-n",
        "prod",
        "exec",
        "-i",
        "api-7f9c",
        "-c",
        "podbench",
        "--",
        "/usr/sbin/sshd",
        "-i",
        "-e",
        "-f",
        "/etc/podbench/sshd_config",
        "-o",
        "LogLevel=ERROR",
    ]


def test_proxy_command_keeps_fd_2_open() -> None:
    # -e is what stops sshd pointing fd 2 at /dev/null; losing it makes
    # containerd tear the exec stream down mid-KEX.
    assert "-e" in proxy_command(TARGET, layout=NON_ROOT)


def test_proxy_command_never_requests_a_tty() -> None:
    # With a real TTY on the ProxyCommand the ssh client hangs indefinitely.
    assert "-t" not in proxy_command(TARGET, layout=ROOT)
    assert "-it" not in proxy_command(TARGET, layout=ROOT)


def test_proxy_command_never_redirects_stderr() -> None:
    # Merging stderr into stdout (2>&1) puts log lines mid-protocol and kills
    # the connection just as surely as closing fd 2 does.
    rendered = proxy_command_string(TARGET, layout=ROOT)
    assert ">" not in rendered
    assert "2>&1" not in rendered
    assert "/dev/null" not in rendered


def test_proxy_command_rejects_a_chatty_log_level() -> None:
    with pytest.raises(ValueError, match="stderr"):
        proxy_command(TARGET, layout=ROOT, log_level="INFO")


def test_proxy_command_carries_context_and_kubeconfig() -> None:
    argv = proxy_command(
        TARGET,
        layout=ROOT,
        kubectl=KubectlInvocation(
            context="staging", kubeconfig="/home/dev/my kubeconfig"
        ),
    )
    assert argv[:5] == [
        "kubectl",
        "--kubeconfig",
        "/home/dev/my kubeconfig",
        "--context",
        "staging",
    ]


def test_proxy_command_string_quotes_for_the_shell() -> None:
    # ssh runs the ProxyCommand through /bin/sh -c.
    rendered = proxy_command_string(
        TARGET,
        layout=ROOT,
        kubectl=KubectlInvocation(kubeconfig="/home/dev/my kubeconfig"),
    )
    assert "'/home/dev/my kubeconfig'" in rendered


def test_control_path_default_fits_the_sun_path_limit() -> None:
    assert control_path_ok(CONTROL_PATH)
    assert expanded_control_path_length(CONTROL_PATH) < SUN_PATH_MAX


def test_a_seat_control_path_still_fits_for_the_longest_alias() -> None:
    # A pod UID is 36 characters and a seat name is bounded by the pod's own
    # name length limit; neither reaches the socket path, because the digest is
    # fixed width. Asserted anyway, since the whole point of the digest is that
    # this arithmetic is knowable before ssh sees the path.
    alias = host_key_alias("3f2c1a90-7b6d-4e21-9a55-0c1e2f3a4b5c", "podbench-10")
    path = seat_control_path(alias)
    assert control_path_ok(path)
    assert expanded_control_path_length(path) == 74


def test_two_seats_in_one_pod_do_not_share_a_control_socket() -> None:
    """The finding-10 regression: ``%C`` alone collides, and silently.

    ``%C`` hashes the resolved HostName, and both stanzas set it to the pod's
    name, so nothing in the alias as typed separates them. Sharing the master
    would mean the second alias reaching the first seat's container *without a
    host-key check*, which is the part that makes this a security bug and not
    only a wrong-container bug.
    """
    uid = "3f2c1a90-7b6d-4e21-9a55-0c1e2f3a4b5c"
    first = seat_control_path(host_key_alias(uid, "podbench-1"))
    second = seat_control_path(host_key_alias(uid, "podbench-2"))
    assert first != second


def test_a_recreated_pod_does_not_inherit_the_control_socket() -> None:
    """Same namespace, same pod name, same seat name — new UID, new socket.

    Deleting a pod is how a seat is reset, and the replacement mints fresh host
    keys. A digest over namespace/pod/container would be identical across that
    reset and hand the new pod the old master.
    """
    seat = "podbench-1"
    before = seat_control_path(host_key_alias("3f2c1a90-7b6d-4e21-9a55-0c1e", seat))
    after = seat_control_path(host_key_alias("b81d4fe3-9c2a-41f7-8e60-5a2b7c1d", seat))
    assert before != after


def test_control_path_guard_catches_a_long_path() -> None:
    long_path = (
        "/home/dev/very/deeply/nested/workspace/directory/tree/"
        "podbench/sockets/controlmasters/%C"
    )
    assert expanded_control_path_length(long_path) >= SUN_PATH_MAX
    assert not control_path_ok(long_path)


def test_ensure_control_dir_is_0700_and_idempotent(tmp_path: Path) -> None:
    target = tmp_path / "cm"
    assert ensure_control_dir(str(target)) == target
    assert stat.S_IMODE(target.stat().st_mode) == 0o700
    target.chmod(0o755)
    ensure_control_dir(str(target))
    assert stat.S_IMODE(target.stat().st_mode) == 0o700


def test_client_config_carries_the_measured_defaults() -> None:
    binding = HostKeyBinding.per_attach(
        "9a1e-uid", "/home/dev/.podbench/known_hosts", "ssh-ed25519 AAAAC3Nz root@pod"
    )
    text = client_config(
        TARGET,
        host_alias="podbench-api",
        identity_file="/home/dev/.podbench/id_ed25519",
        host_key=binding,
        layout=ROOT,
    )
    assert "ServerAliveInterval 15" in text
    assert "ServerAliveCountMax 3" in text
    assert "ControlMaster auto" in text
    # The exact line, not a prefix: `CONTROL_PATH` is a prefix of every seat's
    # socket, so a substring assertion would pass on the bare `%C` this commit
    # exists to remove.
    assert f"    ControlPath {seat_control_path(binding.alias)}\n" in text
    assert "ControlPersist 10m" in text
    assert "IdentitiesOnly yes" in text
    assert "HostKeyAlias podbench-9a1e-uid" in text
    # The spike's StrictHostKeyChecking no is exactly what must never ship.
    assert "StrictHostKeyChecking yes" in text
    assert "StrictHostKeyChecking no" not in text
    # Off unless asked. OpenSSH's client default is already `no`, so the line
    # being absent is the whole of podbench not lending an agent to every seat.
    assert "ForwardAgent" not in text


def test_client_config_rejects_a_long_control_path() -> None:
    binding = HostKeyBinding.from_secret(
        "podbench-api", "/home/dev/.podbench/known_hosts", "ssh-ed25519 AAAAC3Nz"
    )
    with pytest.raises(ValueError, match="AF_UNIX"):
        client_config(
            TARGET,
            host_alias="podbench-api",
            identity_file="/home/dev/.podbench/id_ed25519",
            host_key=binding,
            layout=ROOT,
            control_path=(
                "/home/dev/deeply/nested/workspace/tree/podbench/"
                "sockets/controlmasters/%C"
            ),
        )


def test_host_key_binding_policies() -> None:
    secret = HostKeyBinding.from_secret("podbench-api", "/kh", "ssh-ed25519 AAAA")
    assert secret.policy is HostKeyPolicy.SECRET
    per_attach = HostKeyBinding.per_attach("uid-1", "/kh", "ssh-ed25519 AAAA")
    assert per_attach.policy is HostKeyPolicy.PER_ATTACH
    assert per_attach.alias == host_key_alias("uid-1")


def test_known_hosts_entry_drops_the_comment() -> None:
    binding = HostKeyBinding.per_attach("uid-1", "/kh", "ssh-ed25519 AAAAC3Nz root@pod")
    assert known_hosts_entry(binding) == "podbench-uid-1 ssh-ed25519 AAAAC3Nz\n"


def test_known_hosts_entry_needs_a_key() -> None:
    with pytest.raises(ValueError, match="never observed"):
        known_hosts_entry(HostKeyBinding(HostKeyPolicy.SECRET, "podbench-api", "/kh"))


def test_session_env_is_named_in_the_config_because_sshd_leaks_nothing() -> None:
    """sshd does not pass its own environment to the commands it runs.

    The launcher injects PODBENCH_TARGET_CID into the container spec, but a
    non-interactive ``ssh host 'pids'`` sources no profile and inherits nothing,
    so without SetEnv the helpers silently fall back to guessing which processes
    belong to the target.
    """
    config = sshd_config(
        SshdLayout.for_uid(0),
        {
            "PODBENCH_TARGET_CID": "abc",
            "PODBENCH_NODE_NAME": "n1",
            "PATH": "/app/.venv/bin:/usr/bin",
            "DEBUGINFOD_URLS": "https://debuginfod.debian.net",
        },
    )
    # One directive, not one per variable: sshd resolves each keyword
    # first-match-wins, so a second SetEnv line never takes effect. Found on a
    # real cluster, where only the alphabetically-first variable arrived.
    assert config.count("SetEnv ") == 1
    assert (
        "SetEnv DEBUGINFOD_URLS=https://debuginfod.debian.net "
        "PATH=/app/.venv/bin:/usr/bin "
        "PODBENCH_NODE_NAME=n1 PODBENCH_TARGET_CID=abc" in config
    )


def test_a_name_or_value_sshd_would_misparse_is_dropped() -> None:
    config = sshd_config(
        SshdLayout.for_uid(0),
        {"BAD NAME": "x", "A=B": "y", "SPACED": "has space", "OK": "fine"},
    )
    assert "BAD NAME" not in config
    assert "A=B" not in config
    assert "has space" not in config
    assert "SetEnv OK=fine" in config


def test_the_names_sshd_would_misparse_are_reported_to_the_caller() -> None:
    """Dropping them is not enough. The set carries ``PATH`` now, and a seat
    that loses it silently is the defect this route exists to fix, so the
    caller is handed the names to say so."""
    assert unsafe_set_env({"PATH": "/opt/my tools/bin", "OK": "fine"}) == ("PATH",)
    assert unsafe_set_env({"A=B": "y", "BAD NAME": "x"}) == ("A=B", "BAD NAME")
    assert unsafe_set_env({"PODBENCH_TARGET_CID": "abc"}) == ()


def test_no_session_env_leaves_the_config_as_it_was() -> None:
    assert sshd_config(SshdLayout.for_uid(0)) == sshd_config(SshdLayout.for_uid(0), {})


def test_forward_agent_is_one_line_and_only_when_asked() -> None:
    """The exact line, because it is the whole of the mechanism.

    OpenSSH's two defaults do the rest - the client's ``ForwardAgent`` is
    ``no`` and sshd's ``AllowAgentForwarding`` is ``yes`` - so the seat was
    always willing and the stanza simply never asked.
    """
    binding = HostKeyBinding.per_attach("uid-1", "/kh", "ssh-ed25519 AAAAC3Nz")
    text = client_config(
        TARGET,
        host_alias="podbench-api",
        identity_file="/id",
        host_key=binding,
        layout=ROOT,
        forward_agent=True,
    )
    assert "    ForwardAgent yes\n" in text
    # Still verified, still one identity. The flag widens what the far end may
    # do with the user's keys; it must not loosen anything about the host.
    assert "StrictHostKeyChecking yes" in text
    assert "IdentitiesOnly yes" in text


def test_remote_host_reads_every_ssh_spelling_and_no_others() -> None:
    assert remote_host("git@github.com:x/y.git") == "github.com"
    assert remote_host("ssh://git@github.com/x/y.git") == "github.com"
    # Port 22 is the default, and known_hosts writes the bare name for it.
    assert remote_host("ssh://git@github.com:22/x/y.git") == "github.com"
    assert remote_host("ssh://git@gitlab.example.com:2222/x/y") == (
        "[gitlab.example.com]:2222"
    )
    assert remote_host("GIT@GitHub.COM:x/y.git") == "github.com"
    for other in ("https://github.com/x/y.git", "git://h/x", "/srv/git/y", "", "  "):
        assert remote_host(other) is None, other


def test_git_remote_hosts_keeps_one_of_each() -> None:
    output = (
        "origin\tgit@github.com:x/y.git (fetch)\n"
        "origin\tgit@github.com:x/y.git (push)\n"
        "fork\tssh://git@gitlab.example.com:2222/a/b.git (fetch)\n"
        "public\thttps://github.com/a/b.git (fetch)\n"
        "\n"
    )
    assert git_remote_hosts(output) == ("github.com", "[gitlab.example.com]:2222")


def test_only_the_asked_for_host_is_copied_and_the_comment_goes() -> None:
    """Not the file, and not the pattern it was written under.

    Copying wholesale would hand a seat the user's trust in every machine they
    have ever logged into, which is a wider disclosure than the forwarded agent
    it accompanies.
    """
    known_hosts = (
        "# a comment\n"
        "github.com ssh-ed25519 AAAAC3Nz laptop\n"
        "github.com ssh-rsa AAAAB3Nz\n"
        "internal.example.com ssh-ed25519 SECRET\n"
    )
    assert forge_known_hosts(known_hosts, ["github.com"]) == (
        "github.com ssh-ed25519 AAAAC3Nz",
        "github.com ssh-rsa AAAAB3Nz",
    )


def test_a_hashed_known_hosts_is_matched_rather_than_missed() -> None:
    """``ssh-keygen -H`` is common, and skipping it would find nothing quietly.

    The entry is copied under the plaintext name it matched, which is narrower
    than the hash and readable by whoever next looks at the seat's file - the
    pod already holds a git remote naming that host.
    """
    import base64
    import hashlib
    import hmac

    salt = b"0123456789abcdefffff"
    digest = hmac.new(salt, b"github.com", hashlib.sha1).digest()
    entry = (
        f"|1|{base64.b64encode(salt).decode()}|{base64.b64encode(digest).decode()}"
        " ssh-ed25519 AAAAC3Nz\n"
    )
    assert forge_known_hosts(entry, ["github.com"]) == (
        "github.com ssh-ed25519 AAAAC3Nz",
    )
    assert forge_known_hosts(entry, ["gitlab.example.com"]) == ()


def test_a_bracketed_port_entry_is_not_read_as_a_character_class() -> None:
    """fnmatch would take ``[gitlab.example.com]`` for a set of characters.

    Every known_hosts entry for a non-default port begins with a bracket, so
    the miss would be silent and would look like "you have never trusted it".
    """
    known_hosts = "[gitlab.example.com]:2222 ssh-ed25519 AAAAC3Nz\n"
    assert forge_known_hosts(known_hosts, ["[gitlab.example.com]:2222"]) == (
        "[gitlab.example.com]:2222 ssh-ed25519 AAAAC3Nz",
    )


def test_a_revoked_key_is_never_copied_as_a_trusted_one() -> None:
    """Dropping the marker would invert the line's meaning.

    ``@revoked`` names a key the user has refused; rewritten without it, the
    seat would treat exactly that key as the forge's.
    """
    known_hosts = (
        "@revoked github.com ssh-rsa COMPROMISED\n"
        "@cert-authority *.example.com ssh-ed25519 CA\n"
    )
    assert forge_known_hosts(known_hosts, ["github.com", "git.example.com"]) == ()


def test_a_negated_pattern_still_refuses() -> None:
    known_hosts = "*.example.com,!secret.example.com ssh-ed25519 AAAAC3Nz\n"
    assert forge_known_hosts(known_hosts, ["git.example.com"]) == (
        "git.example.com ssh-ed25519 AAAAC3Nz",
    )
    assert forge_known_hosts(known_hosts, ["secret.example.com"]) == ()
