"""Prepare a seat to serve SSH over a ``kubectl exec`` stream."""

from __future__ import annotations

import argparse
import json
import os
import pwd
import stat
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

PUBLIC_KEY_ENV = "PODBENCH_SSH_PUBLIC_KEY"
SEAT_USER = "podbench"
PYTHON = "/app/.venv/bin/python"


@dataclass(frozen=True)
class ServerInfo:
    login: str
    host_public_key: str
    config_path: str


@dataclass(frozen=True)
class ServerLayout:
    home: Path
    config: Path
    host_key: Path
    authorized_keys: Path


def server_layout(uid: int | None = None) -> ServerLayout:
    own_uid = os.geteuid() if uid is None else uid
    home = Path("/root" if own_uid == 0 else f"/tmp/podbench-{own_uid}")
    base = Path("/etc/podbench") if own_uid == 0 else home / ".podbench"
    return ServerLayout(
        home=home,
        config=base / "sshd_config",
        host_key=base / "ssh_host_ed25519_key",
        authorized_keys=home / ".ssh" / "authorized_keys",
    )


def _write(path: Path, text: str, mode: int) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    path.write_text(text)
    path.chmod(mode)


def _login_name(uid: int) -> str | None:
    try:
        return pwd.getpwuid(uid).pw_name
    except KeyError:
        return None


def _ensure_login(layout: ServerLayout, uid: int, gid: int) -> str:
    if login := _login_name(uid):
        return login
    try:
        claimed_uid = pwd.getpwnam(SEAT_USER).pw_uid
    except KeyError:
        claimed_uid = None
    if claimed_uid is not None and claimed_uid != uid:
        raise RuntimeError(
            f"login name {SEAT_USER!r} already belongs to uid {claimed_uid}"
        )

    extrausers = Path("/var/lib/extrausers/passwd")
    serves = uid >= 500 and (gid >= 500 or gid == 100)
    target = (
        extrausers if serves and os.access(extrausers, os.W_OK) else Path("/etc/passwd")
    )
    if not target.is_file() or not os.access(target, os.W_OK):
        raise RuntimeError(
            f"uid {uid} has no NSS identity and {target} is not writable"
        )
    entry = f"{SEAT_USER}:x:{uid}:{gid}:podbench seat:{layout.home}:/bin/bash"
    existing = target.read_text()
    if entry not in existing.splitlines():
        with target.open("a", encoding="utf-8") as stream:
            stream.write(
                ("" if not existing or existing.endswith("\n") else "\n") + entry + "\n"
            )
    login = _login_name(uid)
    if login is None:
        raise RuntimeError(f"NSS did not resolve uid {uid} after updating {target}")
    return login


def _public_keys(text: str) -> list[str]:
    keys: list[str] = []
    for raw in text.splitlines():
        key = raw.strip()
        if not key:
            continue
        fields = key.split()
        if len(fields) < 2 or not fields[0].startswith(("ssh-", "ecdsa-", "sk-")):
            raise RuntimeError("the SSH public key is not in OpenSSH public-key format")
        if key not in keys:
            keys.append(key)
    if not keys:
        raise RuntimeError("no SSH public key was supplied")
    return keys


def _ensure_authorized_keys(path: Path, public_key: str) -> None:
    existing = path.read_text().splitlines() if path.is_file() else []
    merged: list[str] = []
    for key in [
        *[line.strip() for line in existing if line.strip()],
        *_public_keys(public_key),
    ]:
        if key not in merged:
            merged.append(key)
    _write(path, "\n".join(merged) + "\n", 0o600)
    path.parent.chmod(0o700)


def _ensure_host_key(path: Path) -> None:
    public = Path(f"{path}.pub")
    if path.is_file() and public.is_file():
        return
    if path.is_file():
        result = subprocess.run(
            ["ssh-keygen", "-y", "-f", str(path)],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode:
            raise RuntimeError(result.stderr.strip() or "could not read SSH host key")
        _write(public, result.stdout.strip() + "\n", 0o644)
        return
    public.unlink(missing_ok=True)
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    result = subprocess.run(
        ["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-f", str(path)],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "ssh-keygen failed")


def _ensure_config(layout: ServerLayout, *, root: bool) -> None:
    lines = [
        "# Generated by podbench; do not edit.",
        f"HostKey {layout.host_key}",
        f"AuthorizedKeysFile {layout.authorized_keys}",
        "UsePAM no",
        "PasswordAuthentication no",
        "KbdInteractiveAuthentication no",
        "PermitEmptyPasswords no",
        "Subsystem sftp /usr/lib/openssh/sftp-server",
    ]
    path = os.environ.get("PATH", "")
    if path and not any(character.isspace() for character in path):
        lines.insert(2, f"SetEnv PATH={path}")
    if root:
        Path("/run/sshd").mkdir(mode=0o755, parents=True, exist_ok=True)
        lines.insert(3, "PermitRootLogin prohibit-password")
    else:
        lines.append("StrictModes no")
    _write(layout.config, "\n".join(lines) + "\n", 0o600)
    result = subprocess.run(
        ["/usr/sbin/sshd", "-t", "-f", str(layout.config)],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "sshd rejected its configuration")


def ensure_server(public_key: str) -> ServerInfo:
    uid, gid = os.geteuid(), os.getegid()
    layout = server_layout(uid)
    layout.home.mkdir(mode=0o700, parents=True, exist_ok=True)
    if uid == 0:
        database = Path("/var/lib/extrausers/passwd")
        if database.is_file():
            database.chmod(stat.S_IMODE(database.stat().st_mode) & ~0o022)
    login = _ensure_login(layout, uid, gid)
    _ensure_authorized_keys(layout.authorized_keys, public_key)
    _ensure_host_key(layout.host_key)
    _ensure_config(layout, root=uid == 0)
    host_public_key = Path(f"{layout.host_key}.pub").read_text().strip()
    return ServerInfo(login, host_public_key, str(layout.config))


def _idle() -> None:
    while True:
        try:
            while os.waitpid(-1, os.WNOHANG)[0]:
                pass
        except ChildProcessError:
            pass
        time.sleep(5)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ensure", action="store_true")
    args = parser.parse_args(argv)
    public_key = sys.stdin.read() if args.ensure else os.environ.get(PUBLIC_KEY_ENV, "")
    try:
        info = ensure_server(public_key)
    except (OSError, RuntimeError) as error:
        print(f"podbench SSH setup failed: {error}", file=sys.stderr)
        if args.ensure:
            return 1
    else:
        if args.ensure:
            print(json.dumps(asdict(info)))
            return 0
    _idle()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
